package broker.model;

public enum MessageType {
    REGISTER_REQUEST,
    REGISTER_OK,
    REGISTER_FAIL,

    LOGIN_REQUEST,
    LOGIN_OK,
    LOGIN_FAIL,

    AUTH_REQUEST,
    AUTH_CHALLENGE,
    AUTH_RESPONSE,
    AUTH_OK,
    AUTH_FAIL,

    CREATE_TOPIC,
    SUBSCRIBE,
    UNSUBSCRIBE,
    PUBLISH,
    DELIVER,

    SUCCESS,
    ERROR,

    DOWNLOAD_PENDING,
    DOWNLOAD_OK,

    LIST_TOPICS_REQUEST,
    LIST_TOPICS_RESPONSE,

    DISCONNECT,
    
    BROKER_CERT,
    BROKER_CERT_OK,
    BROKER_CERT_FAIL,
    
    SESSION_KEY_EXCHANGE,
    SESSION_KEY_OK,
    SESSION_KEY_FAIL,
    
    TOPIC_KEY_SHARE,
    TOPIC_KEYS_SYNC_DONE,
}