package broker.model;

public enum MessageType {

    CREATE_TOPIC,
    SUBSCRIBE,
    UNSUBSCRIBE,
    PUBLISH,
    DELIVER,
    SUCCESS,
    ERROR,
    
    REGISTER_REQUEST,
    REGISTER_OK,
    REGISTER_FAIL,
    LOGIN_REQUEST,
    LOGIN_OK,
    LOGIN_FAIL,

    AUTH_REQUEST,
    AUTH_CHALLENGE,
    AUTH_RESPONSE,
    AUTH_OK,
    AUTH_FAIL,

    DISCONNECT,
    DOWNLOAD_PENDING,
    DOWNLOAD_OK,
    LIST_TOPICS_REQUEST,
    LIST_TOPICS_RESPONSE
}